[package]
name = "zkproof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "3.2.1"
merlin = "3.0.0"
rand_core = { version = "0.5", features = ["getrandom"] }
spartan = "0.4.1"
